--MemberDao.getMember(int page)

SELECT * FROM(SELECT ROWNUM NUM ,A.* FROM(SELECT * FROM MEMBERS ORDER BY REGDATE DESC)A)WHERE NUM BETWEEN 11 AND 20; 



SELECT * 
FROM (SELECT ROW_NUMBER() OVER(ORDER BY REGDATE DESC)NUM,MEMBERS.* FROM MEMBERS)A
WHERE NUM BETWEEN 11 AND 20;

SELECT * FROM MEMBERS